local M = {
	arm_flex = "󰿖",
	rainbow = "",
	skull = "󰚌",
	skull_2 = "",
	autofix = "",
	success = "",
	statusline = { Error = "󰯈", Warn = "", Hint = "", Info = "󰙎" },
	git = {
		Add = "+",
		Change = "~",
		Delete = "-",
	},
	kinds = {
		Array = "󰅪",
		Branch = "",
		Boolean = "◩",
		Copilot = "",
		Class = "󰠱",
		Color = "󰏘",
		Constant = "󰏿",
		Constructor = "",
		Enum = "",
		EnumMember = "",
		Event = "",
		Field = "󰆨",
		File = "󰈙",
		Folder = "󰉋",
		Function = "ƒ",
		Interface = "",
		Key = "",
		Keyword = "󰌋",
		Method = "󰆧",
		Module = "󰏗 ",
		Namespace = "󰅩",
		Number = "󰎠",
		Null = "󰟢",
		Object = "⦿",
		Operator = "+",
		Package = "󰏗",
		Property = "󰜢",
		Reference = "",
		Snippet = "",
		String = "𝓐",
		Struct = "󰙅",
		Text = "",
		TypeParameter = "󰆩",
		Unit = "",
		Value = "󰎠",
		Variable = "󰀫",
	},
	diagnostics = {
		Error = "e",
		Warn = "w",
		Hint = "h",
		Info = "i",
	},
}

return M
